### PR TITLE
Aligned FastText embeddings

### PR DESCRIPTION
**Pull request by floscha**
Adds a boolean _aligned_ option to the FastText object's constructor.

If set to *True*, the FastText embeddings will be initialized with the aligned MUSE embeddings (see details [here](https://github.com/facebookresearch/MUSE)).

If not specified or set to *False*, the regular FastText embeddings are used. This way, the PR does not break any code written before the PR.

Example usage:
```python
>>> from torchnlp.word_to_vector import FastText
>>> from scipy.spatial.distance import euclidean as dist

# Load aligned FastText embeddings for English and French
en_vectors = FastText(aligned=True)
fr_vectors = FastText(language='fr', aligned=True)

# Compare the euclidean distances of semantically related vs unrelated words
>>> dist(en_vectors['car'], fr_vectors['voiture'])
0.61194908618927
>>> dist(en_vectors['car'], fr_vectors['baguette'])
1.2417925596237183

### CODE REVIEW

**Comment by PetrochukM** [comment]
Rerunning this tests. Found a bug that prevented your test from being run on .travis.

I suspect your test will fail because you did not add a mock file for fast_text: "pytorch-nlp/tests/_test_data/fast_text/wiki.simple.vec"

The idea of the "mock file" and "mock_urlretrieve" is to mock a download; therefore, you need to download aligned FastText embeddings and add it to the "pytorch-nlp/tests/_test_data/fast_text/" folder.

**Comment by PetrochukM** [comment]
Please rebase master when you get a chance ``git rebase master``! Renamed the ``tests/embeddings`` folder to ``tests/word_to_vector``.

**Comment by floscha** [comment]
Thanks for your explanation on how you use mock files for testing. I wasn't aware of this before. I have now fixed the test according to your instructions and it passes.

Unfortunately, after rebasing, *tests/nn/test_attention.py::TestAttention::test_forward* now fails for Python 3.5 only (see https://travis-ci.org/PetrochukM/PyTorch-NLP/jobs/365802591#L855). Any idea what caused this test to break?

**Comment by PetrochukM** [comment]
Looks like it is a rounding error, WOW! I'll fix it.

image

**Comment by PetrochukM** [comment]
You did it! Thanks for your contribution!

**Pull request merged**
